### ISSUE TITLE
Bugs occur when running gsutil cp

### ISSUE THREAD

**Issue by Len-Li** [RalphMao/Waymo-Dataset-Tool#2]
Hello, thanks for your kindness sharing! When I run your code, a bug occur when it goes `gsutil cp gs://waymo_open_dataset_v_1_0_0/validation
/validation_0000.tar ./` , which outputs `ServiceException: 401 Anonymous caller does not have storage.objects.get access to waymo_open_dataset_v_1_0_0/validation/validation_0000.tar.` It seems like I don't have permission to get data. Could you give me a hand? Thank you.

**Comment by Len-Li** [comment]
#https://github.com/waymo-research/waymo-open-dataset/issues/109
What occurs this bug is that after `pip install gsutil`, I haven't login my google account. So using `gsutil config` can solve the permission problem(remember to use the same account register in waymo.com/open).

**Comment by Ri-Bai** [comment]
Hello，are you  solve this question？ I have the same  problem

**Comment by Len-Li** [comment]
> Hello，are you solve this question？ I have the same problem

Just register in waymo open dataset website and sign in your google account in your computer.

**Comment by Ri-Bai** [comment]
> > Hello，are you solve this question？ I have the same problem
> 
> Just register in waymo open dataset website and sign in your google account in your computer.

![image](https://user-images.githubusercontent.com/74802021/129572683-8299aac8-ea3b-450a-abe5-a367a12d8940.png)
I registered and went to Google Cloud Platform .But the access to the tar file is useless.
the process is error when I download about 4g

**Comment by Ri-Bai** [comment]
> > Hello，are you solve this question？ I have the same problem
> 
> Just register in waymo open dataset website and sign in your google account in your computer.

![image](https://user-images.githubusercontent.com/74802021/129573253-1dc7b174-78bf-4e30-b152-9826603a19a0.png)
 I tried to download the file one by one .but it also meets errors. I don not know where is incorrect. I  have registered with my google account .

**Comment by RalphMao** [comment]
@Baser-Bai It looks like you are having some network issue. If you cannot download the file from browser, then this tool cannot either. Maybe try downloading it with a proxy.

**Comment by Ri-Bai** [comment]
@RalphMao @Len-Li ，Thank you for your answer. The problem I met have solved. the error reason is that I used the win system to download instead of using Linux. So, I do the same work with Ubuntu 18.04 and it' works. Thank you for your help again.
