### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by bilalsattar** [RalphMao/Waymo-Dataset-Tool#3]
What is the difference between this repo and https://github.com/Yao-Shao/Waymo_Kitti_Adapter?

**Comment by RalphMao** [comment]
Not familiar with Yao Shao's repo. After a glance I think his repo provides a wider range of data adaption (like 3d objects). This repo provides a batch download tool which saves your time from downloading every segments one by one.

**Comment by bilalsattar** [comment]
Thanks for the feedback
